fun main(){
    println("Напишите 1, если хотите узнать информацию о кинотеатре, если хотите узнать информацию о собак, то напишите 2")
    var X = readLine()!!.toInt()
    if (X==1){
        println("Информация о фильме:")
        var Film=Cinema("Форсаж","В 14:30","250 ₽","12А,большой","40 зрителей")
        Film.FilmName()
        Film.Seans()
        Film.Ticket()
        Film.Hall()
        Film.Spectaters()
        var Film1=Cinema("Гарри Поттер","В 15:30","270 ₽","12А,большой","20 зрителей")
        Film1.FilmName()
        Film1.Seans()
        Film1.Ticket()
        Film1.Hall()
        Film1.Spectaters()
        var Film2=Cinema("Форсаж 10","В 17:30","450 ₽","12А,большой","50 зрителей")
        Film2.FilmName()
        Film2.Seans()
        Film2.Ticket()
        Film2.Hall()
        Film2.Spectaters()
    }
    if (X==2){
        println("Информация о собаке:")
        var Dog1=Dog("Боец","Овчарка","1 метр","Чёрный","20 килограмм","Добрый")
        Dog1.NickName()
        Dog1.Breed()
        Dog1.Height()
        Dog1.Color()
        Dog1.Weight()
        Dog1.Personality()
        var Dog2=Dog("Сёма","Хачки","1 метр","Чёрный","20 килограмм","Добрый")
        Dog2.NickName()
        Dog2.Breed()
        Dog2.Height()
        Dog2.Color()
        Dog2.Weight()
        Dog2.Personality()
        var Dog3=Dog("Шарик","Дворяга","1 метр","Серый","15 килограмм","Добрый")
        Dog3.NickName()
        Dog3.Breed()
        Dog3.Height()
        Dog3.Color()
        Dog3.Weight()
        Dog3.Personality()
    }
}